// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqBREvVCdOn7qw7EnqOrSlIzx2UedIh50',
    appId: '1:183517778188:web:394ea6b31a837e9b64f929',
    messagingSenderId: '183517778188',
    projectId: 'athancaht',
    authDomain: 'athancaht.firebaseapp.com',
    storageBucket: 'athancaht.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvGOwGy3hiP2GRmfZ-td5LonXKXbeK_T4',
    appId: '1:183517778188:android:08f724258bfcaca864f929',
    messagingSenderId: '183517778188',
    projectId: 'athancaht',
    storageBucket: 'athancaht.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmBisYMtbEHFXi5iy83nl5m53MwMV8YUI',
    appId: '1:183517778188:ios:80bfaf2708a006ec64f929',
    messagingSenderId: '183517778188',
    projectId: 'athancaht',
    storageBucket: 'athancaht.appspot.com',
    iosBundleId: 'com.example.athanMessager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmBisYMtbEHFXi5iy83nl5m53MwMV8YUI',
    appId: '1:183517778188:ios:5eacb4041eb08c4664f929',
    messagingSenderId: '183517778188',
    projectId: 'athancaht',
    storageBucket: 'athancaht.appspot.com',
    iosBundleId: 'com.example.athanMessager.RunnerTests',
  );
}
